### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by PSilvioVidal** [deansaice/TAMDepth#1]
Where did you get your pre-trained weights?
how do i solve this error?
(TAMDepth) nos@nos-Nitro-AN515-58:~/TAMDepth$ python /home/nos/TAMDepth/test_simple.py --load_weights_folder /home/nos/TAMDepth/weights/seu_pasta_de_pesos --image_path /home/nos/TAMDepth/test_images/test_image.jpeg --output_path /home/nos/TAMDepth/test_output/
/home/nos/anaconda3/envs/TAMDepth/lib/python3.7/site-packages/mmcv/__init__.py:21: UserWarning: On January 1, 2023, MMCV will release v2.0.0, in which it will remove components related to the training process and add a data transformation module. In addition, it will rename the package names mmcv to mmcv-lite and mmcv-full to mmcv. See https://github.com/open-mmlab/mmcv/blob/master/docs/en/compatibility.md for more details.
  'On January 1, 2023, MMCV will release v2.0.0, in which it will remove '
-> Loading model from  mypretrain/smt_b_adapter_640/
Loading encoder from: mypretrain/smt_b_adapter_640/encoder.pth
Traceback (most recent call last):
  File "/home/nos/TAMDepth/test_simple.py", line 296, in <module>
    test_simple(args)
  File "/home/nos/TAMDepth/test_simple.py", line 93, in test_simple
    encoder_dict = torch.load(encoder_path)
  File "/home/nos/anaconda3/envs/TAMDepth/lib/python3.7/site-packages/torch/serialization.py", line 771, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/nos/anaconda3/envs/TAMDepth/lib/python3.7/site-packages/torch/serialization.py", line 270, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/nos/anaconda3/envs/TAMDepth/lib/python3.7/site-packages/torch/serialization.py", line 251, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'mypretrain/smt_b_adapter_640/encoder.pth'

**Comment by deansaice** [comment]
You can download the pre-trained weights in **Trained weights on KITTI** part which stored in google drive. Pls make sure your targert directory is correct when running the corresponding command.
